### PR TITLE
Added udev rules and .sh file to copy them and also changed the name of the device node of the camera

### PR DESCRIPTION
**Pull request by Suryansh470**
@Mayankm96 i have added udev rules file and .sh file to copy them to the required folder of the system .... also i have changed the name of the device node of the camera as per the symlink added in the rules ......

### CODE REVIEW

**Comment by Suryansh470** [comment]
Also @Mayankm96  please remove the cam_logitech.launch file from this directory since it implements libuvc_cam for 2 cameras which is not possible at all and this has been tried by me and @naishadhparmar already ..... for that purpose we are using the usb_cam package

**Comment by Mayankm96** [comment]
@Suryansh470 Remove the file you are saying as part of this PR.

**Comment by Mayankm96** [comment]
Also add other udev rules too.

**Comment by Suryansh470** [comment]
okay i am committing after removing that file and also other udev rules will be added by tonight...

**Comment by Suryansh470** [comment]
Added udev rules for arduino as discussed...

**Pull request merged**
